/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

/**
 *
 * @author ADM
 */
public class Jmanipulacao_de_vetores extends javax.swing.JFrame {
     
    /**
     * Creates new form Jmanipulacao_de_vetores
     */
    public Jmanipulacao_de_vetores() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_valor = new javax.swing.JLabel();
        ct_valor = new javax.swing.JTextField();
        bt_add = new javax.swing.JButton();
        bt_exibir = new javax.swing.JButton();
        bt_remover = new javax.swing.JButton();
        bt_maior = new javax.swing.JButton();
        bt_menor = new javax.swing.JButton();
        bt_asc = new javax.swing.JButton();
        bt_desc = new javax.swing.JButton();
        lbl_resul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_titulo.setText("Manipulção de vetores");

        lbl_valor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_valor.setText("Valor ");

        ct_valor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        bt_add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_exibir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_exibir.setText("Exibir");
        bt_exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exibirActionPerformed(evt);
            }
        });

        bt_remover.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_remover.setText("Remover");
        bt_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerActionPerformed(evt);
            }
        });

        bt_maior.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_maior.setText("Maior");
        bt_maior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_maiorActionPerformed(evt);
            }
        });

        bt_menor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_menor.setText("Menor");
        bt_menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menorActionPerformed(evt);
            }
        });

        bt_asc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_asc.setText("Order ASC");
        bt_asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ascActionPerformed(evt);
            }
        });

        bt_desc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_desc.setText("Order DESC");
        bt_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descActionPerformed(evt);
            }
        });

        lbl_resul.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_resul.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_valor)
                        .addGap(18, 18, 18)
                        .addComponent(ct_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_exibir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_remover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_maior, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_menor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_asc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_desc))
                    .addComponent(lbl_resul, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_titulo)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valor)
                    .addComponent(ct_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add)
                    .addComponent(bt_exibir)
                    .addComponent(bt_remover)
                    .addComponent(bt_maior)
                    .addComponent(bt_menor)
                    .addComponent(bt_asc)
                    .addComponent(bt_desc))
                .addGap(74, 74, 74)
                .addComponent(lbl_resul, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int[] valores = new int[4];
    
    int valor;
    private void print(String texto){
        lbl_resul.setText(texto);
    }
    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        for (int i=0;i< valores.length; i++){ 
                        valor = Integer.parseInt(ct_valor.getText());
               if (valores[i] == 0){
                        valores[i] = valor;
                        print("Valor adicionado");
                        break;
               }
        }            
    }//GEN-LAST:event_bt_addActionPerformed
    
    private void bt_exibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exibirActionPerformed
         
        String resposta = "[ ";
        for (int i = 0; i < valores.length; i++){
            if (i > 0){
                resposta += ", ";
            }
            resposta += String.valueOf(valores[i]);
        }
        resposta += " ]";
        print(resposta) ;
        
        
        
                   
        
    }//GEN-LAST:event_bt_exibirActionPerformed

    private void bt_maiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_maiorActionPerformed
        int maior = valores[0] - valor;
        for (int i=0;i< valores.length; i++){ 
                      
                    
                    if (valores[i] > maior){
                         maior = valores[i];
                         print("Maior valor: [" + maior + "]");
                         
                         
                    }
                        
                    
         } 
                
    }//GEN-LAST:event_bt_maiorActionPerformed

    private void bt_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerActionPerformed
        for (int i=0;i< valores.length; i++){ 
                        valor = Integer.parseInt(ct_valor.getText());
                    if (valores[i] != 0 && valores[i] == valor){
                        valores[i] = 0;
                        print("Valor removido");
                    break;
                    }
         } 
    }//GEN-LAST:event_bt_removerActionPerformed

    private void bt_menorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menorActionPerformed
         int menor = valor + valores[0];        
        for (int i=0;i< valores.length; i++){ 
                       
                    
                    if (valores[i] < menor){
                         menor = valores[i];
                         print("Menor valor: [" + menor + "]");
                         
                         
                    }
                        
                    
         }
    }//GEN-LAST:event_bt_menorActionPerformed

    private void bt_ascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ascActionPerformed
        int pm, aux;
        
        for (int i=0;i< valores.length; i++){ 
            pm = i;
          for (int j= i+1;j< valores.length; j++){            
            if(valores[j]< valores[pm]){
                pm = j;
            }         
                   
         }           
         aux = valores[pm];
         valores[pm]= valores[i]; 
         valores[i] = aux;
        print("Vetor ordenado");
        } 
    }//GEN-LAST:event_bt_ascActionPerformed

    private void bt_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descActionPerformed
          int pma, aux;
        
        for (int i=0;i< valores.length; i++){ 
            pma = i;
          for (int j= i+1;j< valores.length; j++){            
            if(valores[j]> valores[pma]){
                pma = j;
            }         
                   
         }           
         aux = valores[pma];
         valores[pma]= valores[i]; 
         valores[i] = aux;
        print("Vetor ordenado");
        } 
    }//GEN-LAST:event_bt_descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jmanipulacao_de_vetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jmanipulacao_de_vetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jmanipulacao_de_vetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jmanipulacao_de_vetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jmanipulacao_de_vetores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_asc;
    private javax.swing.JButton bt_desc;
    private javax.swing.JButton bt_exibir;
    private javax.swing.JButton bt_maior;
    private javax.swing.JButton bt_menor;
    private javax.swing.JButton bt_remover;
    private javax.swing.JTextField ct_valor;
    private javax.swing.JLabel lbl_resul;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_valor;
    // End of variables declaration//GEN-END:variables

    private String getAddElementos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
