/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceCalculadora;

/**
 *
 * @author ADM
 */
public class CalculadoraB extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraB
     */
    public CalculadoraB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_valor01 = new javax.swing.JLabel();
        lbl_valor2 = new javax.swing.JLabel();
        ct_valor01 = new javax.swing.JTextField();
        ct_valor02 = new javax.swing.JTextField();
        lbl_op = new javax.swing.JLabel();
        cb_op = new javax.swing.JComboBox<>();
        bt_calcular = new javax.swing.JButton();
        lbl_resul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_titulo.setText("Claculadora Basica");

        lbl_valor01.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_valor01.setText("valor 01");

        lbl_valor2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_valor2.setText("valor 02");

        ct_valor01.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ct_valor02.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbl_op.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_op.setText("Opereção");

        cb_op.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cb_op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adição", "Subtração", "Divisão", "Multiplicação" }));
        cb_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opActionPerformed(evt);
            }
        });

        bt_calcular.setText("Calcular");
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });

        lbl_resul.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_resul.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lbl_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_valor2)
                                            .addComponent(lbl_valor01))
                                        .addComponent(lbl_op))
                                    .addComponent(bt_calcular))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_op, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ct_valor01, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ct_valor02, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_resul, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_titulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valor01)
                    .addComponent(ct_valor01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ct_valor02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_valor2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_op)
                    .addComponent(cb_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(bt_calcular)
                .addGap(41, 41, 41)
                .addComponent(lbl_resul, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_opActionPerformed
    Calculadora calculadora = new Calculadora();
    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
    
        double valor01 = Double.parseDouble(ct_valor01.getText());
        double valor02 = Double.parseDouble(ct_valor02.getText());
        int op = cb_op.getSelectedIndex();
        System.out.println("OP"+op);
        switch (op){
            case 0:
                //soma
            lbl_resul.setText(" " + calculadora.somar(valor01, valor02));
            break;
            case 1:
                //subtrair
                lbl_resul.setText(" " + calculadora.subtrair(valor01, valor02));
                break;
            case 2:
                //dividir
                lbl_resul.setText(" " + calculadora.dividir(valor01, valor02));
          
            break;
            case 3:
                //multiplicar
                lbl_resul.setText(" " + calculadora.calculo(valor01, valor02));
                break;
        }

    }//GEN-LAST:event_bt_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcular;
    private javax.swing.JComboBox<String> cb_op;
    private javax.swing.JTextField ct_valor01;
    private javax.swing.JTextField ct_valor02;
    private javax.swing.JLabel lbl_op;
    private javax.swing.JLabel lbl_resul;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_valor01;
    private javax.swing.JLabel lbl_valor2;
    // End of variables declaration//GEN-END:variables
}
